### ISSUE TITLE
BitPay is sending nonce parameter in /tokens request

### ISSUE THREAD

**Issue by cataquil** [bitpay/csharp-bitpay-client#12]

**Comment by ionux** [comment]
Thanks for submitting this issue.  Do you have a patch you could submit, by chance? :)

**Comment by cataquil** [comment]
I ran the code a few times and then it started to work.  Well I logged in anyhow.  I am not sure what the nonce parameter does as I don't see it in the API docs.  

I got the code to generate a key pair and store it on the disc.  Now the program reads this key from the file and gets a pairing code.  I am trying to then submit an invoice. 

I looked for the pairing code here:
https://bitpay.com/api-tokens
and it assocated it with my keypair, well the Client ID at least, which is probably the public key part.
But the program says this pairing code is used.  

So I am not sure if I need to generate a new pairing code each time then, use 
bitpay.authorizeClient(pairingCode);

or I take the pairing code from 
https://bitpay.com/api-tokens that is registered to the Client ID in the .key file stored by the program.

Its a bit confusing.  
the document here:
https://labs.bitpay.com/t/how-to-configure-and-use-the-bitpay-c-client-library/297
has a link to  https://bitpay.com/login
but that page returns a 404

maybe I should open this as a separate issue.

**Comment by ionux** [comment]
I don't believe there is a problem if you're still using the nonce parameter with requests but it does appear the term itself has been removed from the API documentation.  I'll double check with the API team and get back to you, though.  The point of the nonce was to prevent replay attacks since it's an ever-increasing, sequential value.  The API now supports sessions using the requestNumber parameter which functions similarly to the nonce.  For more info, see: https://bitpay.com/api#api-sessions

Thanks for the head's up regarding the broken link to the merchant login page, btw.  Our web team will be adding a redirect for it so all the documentation containing the old link won't need to be combed through and changed.

The Client ID is derived from the public key and is used to verify your public key sent in the x-identity http header.  This used to be called a SIN in the API docs - and it technically is - but Client ID is a friendlier name than Service Identification Number.  If you're getting an error code informing you that a pairing code has already been used then you'll either need to use another pairing code or use the Client ID already associated (paired) with you account.  You do not need to generate a pairing code each time!  It's a one-tme pairing of the Client ID derived from your public key to your merchant account.  Consequently, if you need to generate new keys at some point, you'll need to pair them.

Sorry for the confusion!  It is a complicated topic but the added security and new account features our new API gives you hopefully outweigh the extra bit of programming effort needed to make calls.

**Comment by ionux** [comment]
It's looking like the nonce parameter is ignored by the gateway so this shouldn't be causing any issues.  I'll remove the paramter in an upcoming library release, though, just to clean up the code.  Thanks for reporting this!
